CREATE TABLE IF NOT EXISTS Users(
userID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
firstName varchar(50) NOT NULL,
lastName varchar(50) NOT NULL,
email varchar(50) NOT NULL,
pwd varchar(50) Not NULL
);

CREATE TABLE IF NOT EXISTS Address (
addressId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
userID INTEGER NOT NULL,
country varchar(20) NOT NULL,
city varchar(20) NOT NULL,
postCode INTEGER NOT NULL,
FOREIGN KEY (userID) REFERENCES Users(userID)
);

CREATE TABLE IF NOT EXISTS Product(
productId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
categorieId INTEGER NOT NULL,
name varchar(50) NOT NULL,
description TEXT NOT NULL,
price Float NOT NULL,
stock INTEGER NOT NULL,
FOREIGN KEY (categorieId) REFERENCES Categorie(categorieId)
);

CREATE TABLE IF NOT EXISTS Command(
commandId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
statut INTEGER NOT NULL,
addressId INTEGER NOT NULL,
productId INTEGER NOT NULL,
FOREIGN KEY (addressId) REFERENCES Adress(addressId),
FOREIGN KEY (productId) REFERENCES Product(productId)
);

CREATE TABLE IF NOT EXISTS Invoices (
invoicesId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
commanId varchar(20) NOT NULL
FOREIGN KEY (commanId) REFERENCES Command(commanId)
);

CREATE TABLE IF NOT EXISTS Cart(
cartId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
userID INTEGER NOT NULL,
productId INTEGER NOT NULL,
quantity INTEGER NOT NULL,
total float NOT NULL,
FOREIGN KEY (userID) REFERENCES Users(userID),
FOREIGN KEY (productId) REFERENCES Product(productId)
);

CREATE Table Categorie (
    categorieId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    nom VARCHAR(20) NOT NULL
)